///////////////////////////////////////////////////////////
//  Tantárgykezelõ.cs
//  Implementation of the Class Tantárgykezelõ
//  Generated by Enterprise Architect
//  Created on:      25-ápr.-2013 0:43:00
//  Original author: Esse Zsolt
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using Zeusz;
using System.IO;
using System.Xml.Linq;
using System.Linq;
using System;
namespace Zeusz {
	public class Tantárgykezelõ : ITantárgykezelõ {

		//public Személy m_Személy;
		//public Tantárgy list_tantárgyak;

        List<Tantárgy> beolvasottTantárgyak = new List<Tantárgy>();

		public Tantárgykezelõ(){
		}


        /*private void HallgatóBeolvasás()
        {
             beolvasottTantárgyak.Clear();
            try
            {

                XDocument doc = XDocument.Load("Hallgató.xml");

                foreach (var p in doc.Descendants("Hallgató"))
                {
                    beolvasottTantárgyak.Add(new Hallgató(


                         (string)p.Attribute("Zeuszkód"),
                         (string)p.Element("Név"),
                         (string)p.Element("Lakhely"),
                         (string)p.Element("SzemélyIgazolványSzám"),
                         (DateTime)p.Element("SzületésiDátum"),
                         (string)p.Element("Születésihely"),
                         (bool)p.Element("Aktív"),
                         (bool)p.Element("Végzett"))
                         );
                }
            }
            catch (Exception e) { throw (e); }

        }
        */
        
		//~Tantárgykezelõ(){}

		//public virtual void Dispose(){}


        void XMLLétrehozás_Tantárgy(){
            try
            {
                if (!File.Exists("Tantárgy.xml"))
                {

                    XElement tantárgyak = new XElement("Tantárgyak");
                    tantárgyak.Save("Tantárgy.xml");
                   
                }
            }
            catch (Exception e)
            { throw e; }
        }
        


		/// 
		/// <param name="tantárgy"></param>
		public void Tárgyfelvétel(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgyleadás(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgyhozzáadás(Tantárgy tantárgy){

            XMLLétrehozás_Tantárgy();

            XDocument doc = XDocument.Load("Tantárgy.xml");

            XElement tantárgyElem = new XElement("Tantárgy",
                new XAttribute("tárgykód", tantárgy.Tárgykód),
                new XElement("Tárgynév", tantárgy.Tárgynév),
                new XElement("Helyszín", tantárgy.Helyszín),
                new XElement("Kezdés", tantárgy.KezdésIdõpont.ToString()),
                new XElement("Vége", tantárgy.VégeIdõpont.ToString()),
                new XElement("Hét", tantárgy.Hét),
                new XElement("Oktatók", tantárgy.Oktatók),
                new XElement("Követelmények", tantárgy.Követelmények),
                new XElement("Segédletek", tantárgy.Segédletek));
            doc.Element("Tantárgyak").Add(tantárgyElem);

            doc.Save("Tantárgy.xml");
		}

		/// 
		/// <param name="tárgyról"></param>
		/// <param name="tárgyra"></param>
		public void Tárgymódosítás(string tárgyról, Tantárgy tárgyra){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgytörlés(Tantárgy tantárgy){
            try
            {
                if (File.Exists("Tantárgy.xml"))
                {
                    XDocument doc = XDocument.Load("Tantárgy.xml");
                    var t = from tt in doc.Descendants("Tantárgy")
                            where tt.Attribute("tárgykód").Value == tantárgy.Tárgykód
                            select tt;

                    //kitörölni tt-t
                    t.Remove();
                }
            }
            catch (Exception e)
            {

                throw (e);
            }
		}



		/// 
		/// <param name="tantárgyak"></param>
		public List<Tantárgy> tantárgyListázás(){
            //AB lekérdezés
          List<Tantárgy> tantárgyLista =   new List<Tantárgy>();
          return tantárgyLista;
		}

        public List<Tantárgy> tantárgyListázás(string tanárZeuszkód)
        {
            //AB lekérdezés
            List<Tantárgy> tantárgyLista = new List<Tantárgy>();
            return tantárgyLista;
        }


        public void Tárgymódosítás(Tantárgy tárgyról, Tantárgy tárgyra)
        {
            throw new System.NotImplementedException();
        }
    }//end Tantárgykezelõ

}//end namespace Zeusz