///////////////////////////////////////////////////////////
//  ITantárgykezelõ.cs
//  Implementation of the Interface ITantárgykezelõ
//  Generated by Enterprise Architect
//  Original author: Esse Zsolt
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using Zeusz;
namespace Zeusz {
	public interface ITantárgykezelõ {

		/// 
		/// <param name="tantárgy"></param>
		void Tágyfelvétel(Tantárgy tantárgy);

		/// 
		/// <param name="tantárgy"></param>
		void Tárgyleadás(Tantárgy tantárgy);

		/// 
		/// <param name="tantárgy"></param>
		void Tárgyhozzáadás(Tantárgy tantárgy);

		/// 
		/// <param name="tárgyról"></param>
		/// <param name="tárgyra"></param>
		void Tárgymódosítás(Tantárgy tárgyról, Tantárgy tárgyra);

		/// 
		/// <param name="tantárgy"></param>
		void Tárgytörlés(Tantárgy tantárgy);

		/// 
		/// <param name="tantárgyak"></param>
		List<Tantárgy> tantárgyListázás();
	}//end ITantárgykezelõ

}//end namespace Zeusz