///////////////////////////////////////////////////////////
//  Tantárgykezelõ.cs
//  Implementation of the Class Tantárgykezelõ
//  Generated by Enterprise Architect
//  Created on:      25-ápr.-2013 0:43:00
//  Original author: Esse Zsolt
///////////////////////////////////////////////////////////



using System.Collections.Generic;
using Zeusz;
namespace Zeusz {
	public class Tantárgykezelõ : ITantárgykezelõ {

		//public Személy m_Személy;
		//public Tantárgy list_tantárgyak;

		public Tantárgykezelõ(){
		}

		//~Tantárgykezelõ(){}

		//public virtual void Dispose(){}

		/// 
		/// <param name="tantárgy"></param>
		public void Tágyfelvétel(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgyleadás(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgyhozzáadás(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tárgyról"></param>
		/// <param name="tárgyra"></param>
		public void Tárgymódosítás(string tárgyról, Tantárgy tárgyra){
            throw new System.NotImplementedException();
		}

		/// 
		/// <param name="tantárgy"></param>
		public void Tárgytörlés(Tantárgy tantárgy){
            throw new System.NotImplementedException();
		}



		/// 
		/// <param name="tantárgyak"></param>
		public List<Tantárgy> tantárgyListázás(){
            //AB lekérdezés
          List<Tantárgy> tantárgyLista =   new List<Tantárgy>();
          return tantárgyLista;
		}



        public void Tárgymódosítás(Tantárgy tárgyról, Tantárgy tárgyra)
        {
            throw new System.NotImplementedException();
        }
    }//end Tantárgykezelõ

}//end namespace Zeusz